# Auto-generated by /media/work/git/uefi/edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/media/work/git/uefi/edk2
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/media/work/git/uefi/edk2/BaseTools
fi
if [ -e /media/work/git/uefi/edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//media/work/git/uefi/edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/media/work/git/uefi/edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
